# Generated by Django 3.0.3 on 2020-02-10 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=10, verbose_name='Почтовый индекс')),
                ('region', models.CharField(max_length=50, verbose_name='Область')),
                ('area', models.CharField(blank=True, max_length=50, null=True, verbose_name='Район')),
                ('city', models.CharField(max_length=50, verbose_name='Город/Населенный пункт')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('house', models.CharField(max_length=10, verbose_name='Дом')),
                ('building', models.CharField(max_length=20, verbose_name='Корпус')),
                ('apartment', models.CharField(max_length=10, verbose_name='Квартира')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставка',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Название органищации')),
                ('inn', models.CharField(max_length=13, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=20, verbose_name='КПП')),
            ],
            options={
                'verbose_name': 'Юр. лицо',
                'verbose_name_plural': 'Юр. лица',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=180, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Delivery', verbose_name='Доставка')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Entity', verbose_name='Юридическое лицо')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(choices=[('Банковской картой онлайн', 1), ('Оплата по счету', 2), ('Оплата при получении', 3)], default='Оплата при получении', max_length=30, verbose_name='Тип оплаты')),
                ('paid', models.BooleanField(blank=True, default=False, verbose_name='Оплачено')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплата',
            },
        ),
        migrations.CreateModel(
            name='OrderedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Заказанный продукт',
                'verbose_name_plural': 'Заказанные продукты',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Payment', verbose_name='Оплата'),
        ),
    ]
