# Generated by Django 3.0.3 on 2020-02-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200212_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('В обработке', 1), ('Выполнен', 2), ('Отменен', 3)], default=1, verbose_name='Статус заказа'),
        ),
    ]
