# Generated by Django 3.0.3 on 2020-02-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200212_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'В обработке'), (2, 'Выполнен'), (3, 'Отменен')], default=1, verbose_name='Статус заказа'),
        ),
    ]
