# Generated by Django 3.0.3 on 2020-02-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200212_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproducts',
            name='total',
            field=models.PositiveIntegerField(default=1, verbose_name='Цена позиции'),
            preserve_default=False,
        ),
    ]
