# Generated by Django 3.0.3 on 2020-02-10 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Название категории')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Описание категории')),
                ('svg', models.CharField(choices=[('category-icon-1', 'category-icon-1'), ('category-icon-2', 'category-icon-2'), ('category-icon-3', 'category-icon-3'), ('category-icon-4', 'category-icon-4'), ('category-icon-5', 'category-icon-5'), ('category-icon-6', 'category-icon-6'), ('category-icon-7', 'category-icon-7'), ('category-icon-8', 'category-icon-8'), ('category-icon-9', 'category-icon-9'), ('category-icon-10', 'category-icon-10'), ('category-icon-11', 'category-icon-11'), ('done_icon', 'done_icon'), ('exit-icon', 'exit-icon'), ('file-icon', 'file-icon'), ('heart-icon', 'heart-icon'), ('mail', 'mail'), ('no_photo', 'no_photo'), ('phone', 'phone'), ('wallet', 'wallet')], default='no_photo', max_length=16)),
                ('image', models.ImageField(default='catalog-block-img1.jpg', upload_to='images/categories')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.Category', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории товаров',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название свойства товара')),
            ],
            options={
                'verbose_name': 'Названия свойств товаров',
                'verbose_name_plural': 'Название свойства товара',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Название товара')),
                ('vendor_code', models.CharField(max_length=60, verbose_name='Артикул')),
                ('code', models.CharField(max_length=8, verbose_name='Код')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('count', models.PositiveIntegerField(verbose_name='Кол-во на складе')),
                ('bestseller', models.BooleanField(blank=True, default=False, verbose_name='Лидер продаж')),
                ('discount_multiplier', models.FloatField(blank=True, default=1.0, verbose_name='Множитель скидки (1.0=нет скидки)')),
                ('add_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(default='C:\\Users\\User1\\Documents\\dto\\static\\images\\default-image.jpg', upload_to='images/products', verbose_name='Изображение товара')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('about', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('unit', models.CharField(max_length=10, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название брэнда')),
            ],
            options={
                'verbose_name': 'Бренд продукта',
                'verbose_name_plural': 'Бренды продуктов',
            },
        ),
        migrations.CreateModel(
            name='ProductCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg_flag', models.FileField(upload_to='images/countries', verbose_name='Флаг в формате .svg')),
                ('title', models.CharField(max_length=50, verbose_name='Название страны')),
            ],
            options={
                'verbose_name': 'Страна продукта',
                'verbose_name_plural': 'Страны продуктов',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/product_images/', verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Изображение продукта',
                'verbose_name_plural': 'Изображения продуктов',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.ProductBrand', verbose_name='Брэнд'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.ProductCountry', verbose_name='Страна'),
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Значение поля')),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.FieldType', verbose_name='Название поля')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Свойства товара',
                'verbose_name_plural': 'Свойство товара',
            },
        ),
    ]
