# Generated by Django 3.0.2 on 2020-02-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='D:\\archives\\progr\\place-start\\dto\\static\\images\\default-image.jpg', upload_to='images/products', verbose_name='Изображение товара'),
        ),
    ]
