# Generated by Django 3.0.3 on 2020-02-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200213_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='C:\\Users\\User1\\Documents\\dto\\static\\images\\default-image.jpg', upload_to='images/products', verbose_name='Изображение товара'),
        ),
    ]
