# Generated by Django 3.0.2 on 2020-02-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200214_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='add_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата добавления на сайт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=8, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(null=True, verbose_name='Кол-во на складе'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='D:\\archives\\progr\\place-start\\dto\\static\\images\\default-image.jpg', null=True, upload_to='images/products', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(max_length=60, null=True, verbose_name='Артикул'),
        ),
    ]
