# Generated by Django 3.0.3 on 2020-02-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200217_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='C:\\Users\\User1\\Documents\\dto\\static\\images\\default-image.jpg', null=True, upload_to='images/products', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='Ссылка (Латиница)'),
        ),
    ]
